#!/usr/bin/env python3
"""
SendGrid API Key Migration Script

This script helps migrate hardcoded SendGrid API keys to environment variables.
It will:
1. Extract the hardcoded API key from your Python files
2. Create a .env file with the extracted key
3. Update your Python files to use os.getenv() instead of hardcoded keys
4. Create backups of your original files

Usage:
    python migrate_sendgrid.py [path_to_main.py] [path_to_test_sendgrid.py]
    
Example:
    python migrate_sendgrid.py C:\\BidGoatOfficial\\main.py C:\\BidGoatOfficial\\test_sendgrid.py
"""

import os
import re
import sys
import shutil
from datetime import datetime


def extract_sendgrid_key(file_content):
    """Extract SendGrid API key from file content"""
    # Pattern to match SendGrid API keys
    patterns = [
        r'["\']?(SG\.[a-zA-Z0-9_-]{20,})["\']?',  # Standard SG. prefix
        r'sendgrid_api_key\s*=\s*["\']([^"\']+)["\']',  # Variable assignment
        r'SENDGRID_API_KEY\s*=\s*["\']([^"\']+)["\']',  # Constant assignment
        r'SendGridAPIClient\(["\']([^"\']+)["\']\)',  # In SendGridAPIClient constructor
    ]
    
    for pattern in patterns:
        matches = re.findall(pattern, file_content)
        for match in matches:
            if match.startswith('SG.') and len(match) > 20:
                return match
    
    return None


def backup_file(file_path):
    """Create a backup of the file"""
    if not os.path.exists(file_path):
        return None
    
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    backup_path = f"{file_path}.backup_{timestamp}"
    shutil.copy2(file_path, backup_path)
    print(f"✓ Backup created: {backup_path}")
    return backup_path


def ensure_imports(content):
    """Ensure required imports are present"""
    has_dotenv = 'from dotenv import load_dotenv' in content or 'import dotenv' in content
    has_os = 'import os' in content
    has_load_dotenv_call = 'load_dotenv()' in content
    
    lines = content.split('\n')
    
    # Find where to insert imports (after any shebang or encoding declarations)
    insert_index = 0
    for i, line in enumerate(lines):
        if line.strip().startswith('#') and (i == 0 or 'coding' in line or 'encoding' in line):
            insert_index = i + 1
        elif line.strip() and not line.strip().startswith('#'):
            break
    
    # Add missing imports
    imports_to_add = []
    if not has_dotenv:
        imports_to_add.append('from dotenv import load_dotenv')
    if not has_os:
        imports_to_add.append('import os')
    
    if imports_to_add:
        # Add a blank line before imports if needed
        if insert_index > 0 and lines[insert_index - 1].strip():
            lines.insert(insert_index, '')
            insert_index += 1
        
        for imp in imports_to_add:
            lines.insert(insert_index, imp)
            insert_index += 1
    
    # Add load_dotenv() call if missing
    if not has_load_dotenv_call:
        # Find the end of imports section
        import_end = insert_index
        for i in range(insert_index, len(lines)):
            if lines[i].strip() and not (lines[i].strip().startswith('import ') or 
                                         lines[i].strip().startswith('from ') or
                                         lines[i].strip().startswith('#')):
                import_end = i
                break
        
        lines.insert(import_end, '')
        lines.insert(import_end + 1, '# Load environment variables')
        lines.insert(import_end + 2, 'load_dotenv()')
        lines.insert(import_end + 3, '')
    
    return '\n'.join(lines)


def replace_hardcoded_keys(content, api_key):
    """Replace hardcoded API keys with os.getenv() calls"""
    if not api_key:
        return content
    
    # Patterns to replace
    replacements = [
        (f'"{api_key}"', "os.getenv('SENDGRID_API_KEY')"),
        (f"'{api_key}'", "os.getenv('SENDGRID_API_KEY')"),
        (api_key, "os.getenv('SENDGRID_API_KEY')"),
    ]
    
    modified_content = content
    for old, new in replacements:
        if old in modified_content:
            modified_content = modified_content.replace(old, new)
            print(f"  - Replaced hardcoded key with {new}")
    
    return modified_content


def create_env_file(api_key, project_root='.'):
    """Create .env file with the API key"""
    env_path = os.path.join(project_root, '.env')
    
    if os.path.exists(env_path):
        print(f"⚠ .env file already exists at {env_path}")
        response = input("  Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("  Skipping .env file creation")
            return False
    
    with open(env_path, 'w') as f:
        f.write(f"# SendGrid API Configuration\n")
        f.write(f"# Generated by migrate_sendgrid.py on {datetime.now().isoformat()}\n")
        f.write(f"SENDGRID_API_KEY={api_key}\n")
    
    print(f"✓ Created .env file at {env_path}")
    return True


def migrate_file(file_path, api_key, output_path=None):
    """Migrate a single file"""
    if not os.path.exists(file_path):
        print(f"✗ File not found: {file_path}")
        return False
    
    print(f"\nMigrating: {file_path}")
    
    # Create backup
    backup_file(file_path)
    
    # Read file
    with open(file_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Ensure imports
    content = ensure_imports(content)
    
    # Replace hardcoded keys
    content = replace_hardcoded_keys(content, api_key)
    
    # Write to output file
    output_path = output_path or file_path
    with open(output_path, 'w', encoding='utf-8') as f:
        f.write(content)
    
    print(f"✓ Migration complete: {output_path}")
    return True


def main():
    print("=" * 70)
    print("SendGrid API Key Migration Script")
    print("=" * 70)
    
    # Get file paths from command line or prompt
    if len(sys.argv) >= 3:
        main_py_path = sys.argv[1]
        test_py_path = sys.argv[2]
    else:
        print("\nPlease provide the paths to your Python files:")
        main_py_path = input("Path to main.py (e.g., C:\\BidGoatOfficial\\main.py): ").strip()
        test_py_path = input("Path to test_sendgrid.py: ").strip()
    
    # Extract API key from main.py
    print("\n" + "-" * 70)
    print("Step 1: Extracting API key from main.py")
    print("-" * 70)
    
    if not os.path.exists(main_py_path):
        print(f"✗ Error: File not found: {main_py_path}")
        return 1
    
    with open(main_py_path, 'r', encoding='utf-8') as f:
        main_content = f.read()
    
    api_key = extract_sendgrid_key(main_content)
    
    if not api_key:
        print("✗ Could not find SendGrid API key in main.py")
        print("  The script looks for keys starting with 'SG.'")
        api_key = input("\nPlease enter your SendGrid API key manually: ").strip()
    else:
        print(f"✓ Found API key: {api_key[:10]}...{api_key[-5:]}")
    
    # Create .env file
    print("\n" + "-" * 70)
    print("Step 2: Creating .env file")
    print("-" * 70)
    
    # Determine project root (parent of this script or current directory)
    project_root = os.path.dirname(os.path.abspath(__file__))
    create_env_file(api_key, project_root)
    
    # Migrate main.py
    print("\n" + "-" * 70)
    print("Step 3: Migrating main.py")
    print("-" * 70)
    migrate_file(main_py_path, api_key)
    
    # Migrate test_sendgrid.py
    print("\n" + "-" * 70)
    print("Step 4: Migrating test_sendgrid.py")
    print("-" * 70)
    if os.path.exists(test_py_path):
        migrate_file(test_py_path, api_key)
    else:
        print(f"⚠ File not found: {test_py_path}")
        print("  Skipping test_sendgrid.py migration")
    
    # Summary
    print("\n" + "=" * 70)
    print("Migration Complete!")
    print("=" * 70)
    print("\nNext steps:")
    print("1. Review the migrated files to ensure they look correct")
    print("2. Test your application locally to verify it works")
    print("3. If everything works, you can delete the .backup files")
    print("4. Commit and push your changes to GitHub")
    print("\nIMPORTANT:")
    print("- DO NOT commit the .env file (it's in .gitignore)")
    print("- Keep your .env file secure and never share it")
    print("- Each environment should have its own .env file")
    print("=" * 70)
    
    return 0


if __name__ == '__main__':
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n\nMigration cancelled by user")
        sys.exit(1)
    except Exception as e:
        print(f"\n✗ Error: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
